# Generated by Django 4.1.7 on 2023-03-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_alter_novel_step_alter_novelcontent_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='introduction',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
